site_name: "Grupo Elizabeth Friedman - T02 (2025.1)"
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T02-ELIZABETH-FRIEDMAN
repo_name: GitHub

theme:
  name: material
nav:
  - Home: index.md
  - Contextualização: contextualizacao.md
  - GQM: 
    - Definição: GQM/gqm.md
    - Abstração: GQM/abstracao.md